name: 🐛 Bug Report
description: Report an issue for an egg
title: "[Bug]: "
labels: [Bug]
body:
  - type: markdown
    attributes:
      value: |
          If you see any of the following, go to [Discord](https://discord.gg/pterodactyl) and report your error in a support channel.
          * `A fatal error was encountered while starting this server.`
          * `No server egg configuration could be located; aborting startup.`
  - type: input
    id: panel-version
    attributes:
      label: Panel Version
      description: Version number of your Panel (latest is not a version)
      placeholder: 1.x.x
    validations:
      required: true
  - type: input
    id: wings-version
    attributes:
      label: Wings Version
      description: Version number of your Wings (latest is not a version)
      placeholder: 1.x.x
    validations:
      required: true      
  - type: input
    id: service
    attributes:
      label: Service
      description: Service you are experiencing issues with
      placeholder: minecraft/factorio/etc
    validations:
      required: true          
  - type: dropdown
    id: modified
    attributes:
      label: Modified
      description: Did you add or change things, this includes startup configs/install scripts/variables
      options:
        -  Yes, I modified the egg (will provide details below)
        -  No, I did not modify the egg   
    validations:
      required: true 
  - type: textarea          
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen
      placeholder: Install the server, start it, play
    validations:
      required: true
  - type: textarea      
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened instead
      placeholder: Server crashed with error X
    validations:
      required: true
  - type: textarea       
    id: reproduce-steps
    attributes:
      label: Steps To Reproduce
      description: Step by step what to do to cause the issue
      placeholder: |
       Step 1 Set version to latest
       Step 2 install
       Step 3 Receive error X or Y
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell