name: palworld modded fetch file
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - master
    paths:
      - game_eggs/steamcmd_servers/palworld/**/*
      - .github/scripts/scripts/palworld-modded-fetch.ps1
      - .github/scripts/workflows/palworld-modded-fetch.yml
env:
  DEBUG: true
jobs:
  check_file_update:
    name: Check For File Update
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      REPO_OWNER: "CuteNatalie"
      REPO_NAME: "Palworld-Modded-Server-Linux"
      REPO_URL: ""
      DoUpdate: ""
    steps:
      - run: |
          echo "REPO_URL=${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}" >> $GITHUB_ENV
      - name: Checkout Current Repository
        uses: actions/checkout@v4
        with:
          path: "current"
      - name: Checkout Documentation Repository
        uses: actions/checkout@v4
        if: ${{ env.REPO_URL != '' }}
        env:
          TOKEN: ${{ secrets.PAM }}
        with:
          repository: ${{ env.REPO_URL }}
          token: ${{ env.TOKEN }}
          path: "documentation"
      - name: Do Task
        shell: pwsh
        env:
          TOKEN: ${{ secrets.PAM }}
          pwsh_DEBUG: true
          pwsh_VERBOSE: true
          POWERSHELL_TELEMETRY_OPTOUT: 0
        run: |
          & "./current/.github/scripts/palworld-modded-fetch.ps1"
      - name: Finish Update
        if: ${{ env.DoUpdate != '' && env.DoUpdate != '0' }}
        uses: EndBug/add-and-commit@v9
        with:
          cwd: "./current"
          add: "./game_eggs/steamcmd_servers/palworld/binaries/winmm.zip"
          commit: --signoff
          default_author: github_actions
          message: "update: winmm.zip"
          pathspec_error_handling: exitImmediately
